Errors recorded by Messager.printMessage(ERROR,"error message") do not seem to be counted correctly as final error message reports only 1 error rather than the number printed.
