My most simplified version of the bug:

{code}
fun main(args: Array<String>) {
  var s: String?
  s = null
  try {
    s = "Test"
  } catch (ex: Exception) {}
  println(s)
  if (s != null) {
    println("Always false?")
  }
}
{code}

Compiler shows warning in line "if (s != null) {" that the condition is always false, e.g. "s" is "null". But "s" is not "null"!

The generated code could fail at runtime in some cases (when the try block didn't complete normally), but sometimes it worked.
Reporting a deprecation warning here is very difficult, because it affects too many aspects of type checking