Reproduction:

1. Paste following code in the editor

```
package foo.bar

import java.lang.Exception

fun main() {
    var x: Int? = null

    x = 42

    try {
        println(x)
    } catch ()
}
```

2. Get an exception

NI should be turned on, reproduced on 1.3.50-dev-1431-2019.1