``` kotlin

fun <T : Exception> foo() : T {
    try {
        throw Exception()
    }
    catch(x : T) { // Actually it catches Exception, that is not typesafe
        return x
    }
}

fun main(args: Array<String>) {
    val x = foo<ArithmeticException> ()
}
```

Exception in thread "main" java.lang.ClassCastException: java.lang.Exception cannot be cast to java.lang.ArithmeticException
	at _DefaultPackage$K$2b1b479f.main(K.kt:11)
	at _DefaultPackage.main(K.kt:1)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
