```scala
object i0{
    import i0.i0
    def i0={
        import _
        import
    }
}
```

ME-472031f0cd1b8e6bbcdecb17e2c8a18cf53e32cf

---

```scala
exception occurred while typechecking test.scala
exception occurred while compiling test.scala
scala.MatchError: NoType (of class dotty.tools.dotc.core.Types$NoType$) while compiling test.scala
Exception in thread "main" scala.MatchError: NoType (of class dotty.tools.dotc.core.Types$NoType$)
	at dotty.tools.dotc.typer.ImportInfo.site(ImportInfo.scala:51)
	at dotty.tools.dotc.typer.ImportInfo.compute$1(ImportInfo.scala:149)
	at dotty.tools.dotc.typer.ImportInfo.featureImported(ImportInfo.scala:160)
	at dotty.tools.dotc.core.TypeOps.featureEnabled(TypeOps.scala:309)
	at dotty.tools.dotc.core.TypeOps.featureEnabled$(TypeOps.scala:306)
	at dotty.tools.dotc.core.Contexts$Context.featureEnabled(Contexts.scala:71)
	at dotty.tools.dotc.core.TypeOps.scala2Mode(TypeOps.scala:325)
	at dotty.tools.dotc.core.TypeOps.scala2Mode$(TypeOps.scala:324)
	at dotty.tools.dotc.core.Contexts$Context.scala2Mode(Contexts.scala:71)
	at dotty.tools.dotc.reporting.Reporting.errorOrMigrationWarning(Reporter.scala:102)
	at dotty.tools.dotc.reporting.Reporting.errorOrMigrationWarning$(Reporter.scala:101)
	at dotty.tools.dotc.core.Contexts$Context.errorOrMigrationWarning(Contexts.scala:71)
	at dotty.tools.dotc.typer.Checking$.checkRealizable(Checking.scala:147)
	at dotty.tools.dotc.typer.Typer.$anonfun$typedImport$1(Typer.scala:1787)
	at dotty.tools.dotc.util.Stats$.track(Stats.scala:37)
	at dotty.tools.dotc.typer.Typer.typedImport(Typer.scala:1784)
	at dotty.tools.dotc.typer.Typer.typedUnnamed$1(Typer.scala:2023)
	at dotty.tools.dotc.typer.Typer.typedUnadapted(Typer.scala:2066)
	at dotty.tools.dotc.typer.Typer.$anonfun$typed$2(Typer.scala:2100)
	at dotty.tools.dotc.reporting.trace$.apply(trace.scala:40)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2093)
	at dotty.tools.dotc.typer.Typer.typed(Typer.scala:2112)
```